
var CoreBase = require('../core-base/core-base.js');

require('./core-icon.less');

var component = CoreBase.extend({

    template: require('./core-icon.html'),

    data: {

        /**
         * Tooltip for this icon.
         * @type String
         * @default null
         */
        tooltip: null,

        /**
         * The icon.
         * @type String
         * @default ''
         */
        icon: '',

        /**
         * Icons dictionary.
         * @type Object
         */
        icons: function ()
        {
            return component.icons;
        },

    },

});

component.icons = Object.freeze({
    'phone': '\ue600',
    'mobile': '\ue601',
    'mouse': '\ue602',
    'directions': '\ue603',
    'mail': '\ue604',
    'paperplane': '\ue605',
    'pencil': '\ue606',
    'feather': '\ue607',
    'paperclip': '\ue608',
    'drawer': '\ue609',
    'reply': '\ue60a',
    'reply-all': '\ue60b',
    'forward': '\ue60c',
    'user': '\ue60d',
    'users': '\ue60e',
    'user-add': '\ue60f',
    'vcard': '\ue610',
    'export': '\ue611',
    'location': '\ue612',
    'map': '\ue613',
    'compass': '\ue614',
    'location2': '\ue615',
    'target': '\ue616',
    'share': '\ue617',
    'sharable': '\ue618',
    'heart': '\ue619',
    'heart2': '\ue61a',
    'star': '\ue61b',
    'star2': '\ue61c',
    'thumbsup': '\ue61d',
    'thumbsdown': '\ue61e',
    'chat': '\ue61f',
    'comment': '\ue620',
    'quote': '\ue621',
    'house': '\ue622',
    'popup': '\ue623',
    'search': '\ue624',
    'flashlight': '\ue625',
    'printer': '\ue626',
    'bell': '\ue627',
    'link': '\ue628',
    'flag': '\ue629',
    'cog': '\ue62a',
    'tools': '\ue62b',
    'trophy': '\ue62c',
    'tag': '\ue62d',
    'camera': '\ue62e',
    'megaphone': '\ue62f',
    'moon': '\ue630',
    'palette': '\ue631',
    'leaf': '\ue632',
    'music': '\ue633',
    'music2': '\ue634',
    'new': '\ue635',
    'graduation': '\ue636',
    'book': '\ue637',
    'newspaper': '\ue638',
    'bag': '\ue639',
    'airplane': '\ue63a',
    'lifebuoy': '\ue63b',
    'eye': '\ue63c',
    'clock': '\ue63d',
    'microphone': '\ue63e',
    'calendar': '\ue63f',
    'bolt': '\ue640',
    'thunder': '\ue641',
    'droplet': '\ue642',
    'cd': '\ue643',
    'briefcase': '\ue644',
    'air': '\ue645',
    'hourglass': '\ue646',
    'gauge': '\ue647',
    'language': '\ue648',
    'network': '\ue649',
    'key': '\ue64a',
    'battery': '\ue64b',
    'bucket': '\ue64c',
    'magnet': '\ue64d',
    'drive': '\ue64e',
    'cup': '\ue64f',
    'rocket': '\ue650',
    'brush': '\ue651',
    'suitcase': '\ue652',
    'cone': '\ue653',
    'earth': '\ue654',
    'keyboard': '\ue655',
    'browser': '\ue656',
    'publish': '\ue657',
    'progress-3': '\ue658',
    'progress-2': '\ue659',
    'brogress-1': '\ue65a',
    'progress-0': '\ue65b',
    'sun': '\ue65c',
    'sun2': '\ue65d',
    'adjust': '\ue65e',
    'code': '\ue65f',
    'screen': '\ue660',
    'infinity': '\ue661',
    'light-bulb': '\ue662',
    'creditcard': '\ue663',
    'database': '\ue664',
    'voicemail': '\ue665',
    'clipboard': '\ue666',
    'cart': '\ue667',
    'box': '\ue668',
    'ticket': '\ue669',
    'rss': '\ue66a',
    'signal': '\ue66b',
    'thermometer': '\ue66c',
    'droplets': '\ue66d',
    'table': '\ue66e',
    'statistics': '\ue66f',
    'pie': '\ue670',
    'bars': '\ue671',
    'graph': '\ue672',
    'lock': '\ue673',
    'lock-open': '\ue674',
    'logout': '\ue675',
    'login': '\ue676',
    'checkmark': '\ue677',
    'cross': '\ue678',
    'minus': '\ue679',
    'plus': '\ue67a',
    'cross2': '\ue67b',
    'minus2': '\ue67c',
    'plus2': '\ue67d',
    'cross3': '\ue67e',
    'minus3': '\ue67f',
    'plus3': '\ue680',
    'erase': '\ue681',
    'blocked': '\ue682',
    'info': '\ue683',
    'info2': '\ue684',
    'question': '\ue685',
    'help': '\ue686',
    'warning': '\ue687',
    'cycle': '\ue688',
    'cw': '\ue689',
    'ccw': '\ue68a',
    'shuffle': '\ue68b',
    'arrow': '\ue68c',
    'arrow2': '\ue68d',
    'retweet': '\ue68e',
    'loop': '\ue68f',
    'history': '\ue690',
    'back': '\ue691',
    'switch': '\ue692',
    'list': '\ue693',
    'add-to-list': '\ue694',
    'layout': '\ue695',
    'list2': '\ue696',
    'text': '\ue697',
    'text2': '\ue698',
    'document': '\ue699',
    'docs': '\ue69a',
    'landscape': '\ue69b',
    'pictures': '\ue69c',
    'video': '\ue69d',
    'music3': '\ue69e',
    'folder': '\ue69f',
    'archive': '\ue6a0',
    'trash': '\ue6a1',
    'upload': '\ue6a2',
    'download': '\ue6a3',
    'disk': '\ue6a4',
    'install': '\ue6a5',
    'cloud': '\ue6a6',
    'upload2': '\ue6a7',
    'bookmark': '\ue6a8',
    'bookmarks': '\ue6a9',
    'book2': '\ue6aa',
    'play': '\ue6ab',
    'pause': '\ue6ac',
    'record': '\ue6ad',
    'stop': '\ue6ae',
    'next': '\ue6af',
    'previous': '\ue6b0',
    'first': '\ue6b1',
    'last': '\ue6b2',
    'resize-enlarge': '\ue6b3',
    'resize-shrink': '\ue6b4',
    'volume': '\ue6b5',
    'sound': '\ue6b6',
    'mute': '\ue6b7',
    'flow-cascade': '\ue6b8',
    'flow-branch': '\ue6b9',
    'flow-tree': '\ue6ba',
    'flow-line': '\ue6bb',
    'flow-parallel': '\ue6bc',
    'arrow-left': '\ue6bd',
    'arrow-down': '\ue6be',
    'arrow-up-upload': '\ue6bf',
    'arrow-right': '\ue6c0',
    'arrow-left2': '\ue6c1',
    'arrow-down2': '\ue6c2',
    'arrow-up': '\ue6c3',
    'arrow-right2': '\ue6c4',
    'arrow-left3': '\ue6c5',
    'arrow-down3': '\ue6c6',
    'arrow-up2': '\ue6c7',
    'arrow-right3': '\ue6c8',
    'arrow-left4': '\ue6c9',
    'arrow-down4': '\ue6ca',
    'arrow-up3': '\ue6cb',
    'arrow-right4': '\ue6cc',
    'arrow-left5': '\ue6cd',
    'arrow-down5': '\ue6ce',
    'arrow-up4': '\ue6cf',
    'arrow-right5': '\ue6d0',
    'arrow-left6': '\ue6d1',
    'arrow-down6': '\ue6d2',
    'arrow-up5': '\ue6d3',
    'arrow-right6': '\ue6d4',
    'arrow-left7': '\ue6d5',
    'arrow-down7': '\ue6d6',
    'arrow-up6': '\ue6d7',
    'uniE6D8': '\ue6d8',
    'arrow-left8': '\ue6d9',
    'arrow-down8': '\ue6da',
    'arrow-up7': '\ue6db',
    'arrow-right7': '\ue6dc',
    'menu': '\ue6dd',
    'ellipsis': '\ue6de',
    'dots': '\ue6df',
    'dot': '\ue6e0',
    'cc': '\ue6e1',
    'core-by': '\ue6e2',
    'core-nc': '\ue6e3',
    'core-nc-eu': '\ue6e4',
    'core-nc-jp': '\ue6e5',
    'core-sa': '\ue6e6',
    'core-nd': '\ue6e7',
    'core-pd': '\ue6e8',
    'core-zero': '\ue6e9',
    'core-share': '\ue6ea',
    'core-share2': '\ue6eb',
    'danielbruce': '\ue6ec',
    'danielbruce2': '\ue6ed',
    'github': '\ue6ee',
    'github2': '\ue6ef',
    'flickr': '\ue6f0',
    'flickr2': '\ue6f1',
    'vimeo': '\ue6f2',
    'vimeo2': '\ue6f3',
    'twitter': '\ue6f4',
    'twitter2': '\ue6f5',
    'facebook': '\ue6f6',
    'facebook2': '\ue6f7',
    'facebook3': '\ue6f8',
    'googleplus': '\ue6f9',
    'googleplus2': '\ue6fa',
    'pinterest': '\ue6fb',
    'pinterest2': '\ue6fc',
    'tumblr': '\ue6fd',
    'tumblr2': '\ue6fe',
    'linkedin': '\ue6ff',
    'linkedin2': '\ue700',
    'dribbble': '\ue701',
    'dribbble2': '\ue702',
    'stumbleupon': '\ue703',
    'stumbleupon2': '\ue704',
    'lastfm': '\ue705',
    'lastfm2': '\ue706',
    'rdio': '\ue707',
    'rdio2': '\ue708',
    'spotify': '\ue709',
    'spotify2': '\ue70a',
    'qq': '\ue70b',
    'instagram': '\ue70c',
    'dropbox': '\ue70d',
    'evernote': '\ue70e',
    'flattr': '\ue70f',
    'skype': '\ue710',
    'skype2': '\ue711',
    'renren': '\ue712',
    'sina-weibo': '\ue713',
    'paypal': '\ue714',
    'picasa': '\ue715',
    'soundcloud': '\ue716',
    'mixi': '\ue717',
    'behance': '\ue718',
    'circles': '\ue719',
    'vk': '\ue71a',
    'smashing': '\ue71b'
});

module.exports = component;
